### ISSUE TITLE
Some JSON files in the vivit code are missing

### ISSUE THREAD

**Issue by shandyyyyyy** [noureldien/vivit_pytorch#2]
作者您好，我是来自中国的一名大学生贝耶。最近在使用您开源的vivit代码做毕业设计，但是我在使用您的代码的过程中发现您的annotation文件下很多json文件在网络上找不到，例如augmentation-mappings.json，但是我运行这个代码急需使用这个文件，能否烦请您将这些json文件上传到github，或者是发到我的邮箱w15935476725@gmail.com。万分感谢！
Hello, I'm Beyer, a college student from China. Recently, I was using your open source vivit code for graduation design, but I found that many JSON files under your annotation file could not be found on the network, such as augmentation mappings JSON, but I need this file urgently to run this code. Could you please upload these JSON files to GitHub or send them to my email w15935476725@gmail.com 。 Thank you very much!

**Comment by noureldien** [comment]
Hi Beyer,

Thanks for asking. If you noticed the comments at
https://github.com/noureldien/vivit_pytorch/blob/55d09daf906b0b4a85239ca157c7aa4ea515cec8/datasets/data_sets.py#L25
it says that the code of the data loader is borrowed from another repository
https://github.com/TwentyBN/something-something-v2-baseline/blob/master/data_loader_skvideo.py

I searched GitHub and found it. Have a look here
https://github.com/caspillaga/Conv3DSelfAttention/blob/master/assets/augmentation_mappings.json

Good luck with your studies.
